import type { Metadata } from "next";
// 1. Importe a fonte Roboto
import { Roboto } from "next/font/google";
import "./globals.css";

// 2. Configure a fonte Roboto
const roboto = Roboto({
  variable: "--font-roboto", // Define um nome de variável CSS
  subsets: ["latin"],
  weight: ["400", "700"], // Especifique os pesos que você vai usar
});

export const metadata: Metadata = {
  title: "Accessibility.AI ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>{children}</body>
    </html>
  );
}